@url_dev=http://localhost:8000/v1/api/customer
@api_key=6edb89c59c1c6c7826b204003e952b33a152d208306e42089d68b3c29779d0934ec12c13650c881a8c081026045ba78d9e869f725fa44dee07f6332285c7e4ec
@accessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvYW5nbmNkM0BnbWFpbC5jb20iLCJ1c2VySWQiOiI2NTcwYTYwMmUyZWZkYzYxODYxMDYwZTQiLCJpYXQiOjE3MDI1NzI5MDYsImV4cCI6MTcwMjc0NTcwNn0.A1zle9w5F90nkACUjipv2O-g2nsMf8KMxaGV_qXQUa8mzoDRKTsRQAFyQVXJ1P119X8Iw1E-RBvMzLhUF7YbszdXxtB5wyiFbqYHzTuU5TYeB-iJP_V1yCWsmMD0mbdfpmlZ13S2AkcX2eo91ClL1b_luthvDl6cEHK3N1Wz1mZNpW8ILG6c3rbpiARcgcZL7kiDiH6bLh6BBBebEFJ4tZ7oYyQM-GQrmhYqijwtP7JPR9tjL1nLb5pCC4mktHsJWhvhnr60BzWKbgcWIyZwz9BiO7Sbps-uhnTOURQ5DhXaKKCzchAPFTkJprs-X4zncxjdmUfGN9yBI48Q2OIUzjUbbKM5Xbm-nZZU6l-xOph1rI1V-zt9Rn7eQe1NnIOy7vffzTyrOoPUENpcZR_SOd5VU6pu0KhycoMZag1EDMLs6cZVjsGhBqdijrn9mYuh2aYlpXwz0qjZKGWlk9JIJpO0jUtyVb96900pYlK_T2QrbNqhm2sYenvAhflUxn7MXT6ubLUhSUF_DyXyT4mUHmlFvRH4HD8MuogXs5rdWRqvwzt6OUE9z1rYC3zoLSajyzowsxKhiw3yR7-18ZHabjp07fHKHx1uYKzQxn4VF_8ROlqvFj3DiApk5568d2IjPv36h7w2GUcTgM94lNXBsxub2cZdHq9g-PI9PKBu7PM

### signup
POST {{url_dev}}/signup
Content-Type: application/json
x-api-key: {{api_key}}

{
  "name": "Hoang Nguyen",
  "email": "hoangncd3@gmail.com",
  "password": "1234567@"
}

### login
POST {{url_dev}}/login
Content-Type: application/json
x-api-key: {{api_key}}

{
  "email": "hoangncd3@gmail.com",
  "password": "1234567@"
}

### logout
POST {{url_dev}}/logout
Content-Type: application/json
x-api-key: {{api_key}}
Authorization: {{accessToken}}
x-client-id: 6570a602e2efdc61861060e4

### refresh token
POST {{url_dev}}/refresh-token
Content-Type: application/json
x-api-key: {{api_key}}
Authorization: {{accessToken}}
x-client-id: 6570a602e2efdc61861060e4

{
  "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvYW5nbmNkM0BnbWFpbC5jb20iLCJ1c2VySWQiOiI2NTcwYTYwMmUyZWZkYzYxODYxMDYwZTQiLCJpYXQiOjE3MDI1NzI4NjgsImV4cCI6MTcwMzE3NzY2OH0.ub-ndFltJ1c-4EBh5oSFJtncMhBBCKLI_SX21XnyS_mBMdW0R7Jo5Yu7DR3FY1EKAq-KGHWEdvRwaxIBS0CdYHpMf0YhkY18HqYqfGSATjSxBmFP5WBdNPpguzfOhcUIcDes-cp3GYnR6pS-WlsOY8uyXB8cvudTYiquXUo1fwczSLNsjp_M2gBXjwNxt6o0KxJIft-Zo-TbTAD9QqZa20zkl3o0xarVooXmj7q007Q0t-0sPdCLHaQQnIfnN2PXRKlxIq1cKrFF6pYGdpinB-U-mLIYnNSx3duvd-5TeTV-PjWmymwLLnJh2S1HrjarXcLYDWfNg341aicHiMyPPXoNqfQZ0k7cml5UbrsV7bYO8AmrG3dvQz4hctjpVD--zjMX6Tp8OL3Pt03-DEyg2EjvPY9ENqCqm19_rZDDRpO_PP-2nR5sjreJ9dCqLRGiNt7lU3vCmxBdVnC_A6FWXiPcGzgF-4Z4rUXgHHwApTeld4G5uPLyzWkx64npiV9k8d9ZkvLJGFULeSuZn4B00W3jo7n8yeqHeEIk8mVPItomgqzvjnpA1wxB8fx713I_DEf_U6lxXjYo48pDV3SiGQM7dGH8rDWxF3AW5xO3GVg8usTlnUrzqLso00ikMyNfy4DYXHu1XpsKlSSzpLo1BA2Vw5d3AuI26fmP4BUo0RI"
}
