@url_dev=http://localhost:8000/v1/api/customer
@api_key=6edb89c59c1c6c7826b204003e952b33a152d208306e42089d68b3c29779d0934ec12c13650c881a8c081026045ba78d9e869f725fa44dee07f6332285c7e4ec
@accessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvYW5nbmNkM0BnbWFpbC5jb20iLCJ1c2VySWQiOiI2NTcwYTYwMmUyZWZkYzYxODYxMDYwZTQiLCJpYXQiOjE3MDI5MDc1MDEsImV4cCI6MTcwMzA4MDMwMX0.A71rww0OW212ChtUeO7kvMqkot7N_J8F3Ls2DqZyZjsLXwEAPq5J71vwPRV04v-Z3UdYw_ZNiZtmFwcfsj3pb706n_69MeU6Pf4keVRecJiD6IrC_8zqp1mcVmpo6gVyPNALz8Inusz_6N5w9q0bbp-6KfzDw0JLQVy7UCuR010LKU0g609zFRf2jeWkwBtdkl0ewxCkCAuoKFI4-Q4lC0Q6sIucxd9xBhd9E9e3EmyYA9o4VOVtI7_eKb4s77eoxuyC0BTIxenG9asu-H-lTEUqak7DIYaLFtN7Mh3m8UsK8nylrpFJqq7WCBzkSyq0AvPUZkSLtxNoPTBOgxkVyLegjfzyTspoAioM7YiwtPBRgX8zGNjVOQaTiMK7Y3JUvJQK4nL-WAh60H9OEF68ykaqPuWHF7zNShWvLqZuiiwoCcD-4k2Syb8-OStRIcn7r1TK-p9WdwdOoln0Yia40xtll477MSMQR0IqKgx7M1LE_HrvLjWnhEb2GXZwDJKbAIYWr7XfNQzliYtaXLUW7zljy330Zw-uOJibBvE_ZC93y9moS1Khb2-DQMg4sP-HgKNV_2IDf30rxjgmHfkrUiejr64XrN-WbvJNiTC0Fsf6HF_2SFBK7xLu_30SRsRA_T34mVfiGEGTYMFL1r6VqA6OagFsp-Gtk3l422j_1dY

### create product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: {{api_key}}
Authorization: {{accessToken}}
x-client-id: 6570a602e2efdc61861060e4

{
  "title": "Product Electronic 03",
  "type": "electronics",
  "thumbnail": "http://image",
  "price": 1000,
  "quantity": 100,
  "shop": "6570a602e2efdc61861060e4",
  "attributes": {
    "manufacturer": "Manufacturer 03",
    "model": "Model 03",
    "color": "Red"
  },
  "description": "Product Electronic 03 Description"
}
