@url_dev=http://localhost:8000/v1/api/customer
@api_key=6edb89c59c1c6c7826b204003e952b33a152d208306e42089d68b3c29779d0934ec12c13650c881a8c081026045ba78d9e869f725fa44dee07f6332285c7e4ec
@accessToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvYW5nbmNkMTNAZ21haWwuY29tIiwidXNlcklkIjoiNjU2ZjU0MGM3YmIzZGZjMGI3ODk1YzA4IiwiaWF0IjoxNzA0Mzg3MDkxLCJleHAiOjE3MDQ1NTk4OTF9.VZAU4y28S4G2bzRds0GDmPylPAfZAWtezkstnDbcsMA9VdJsWwXV3Hsgsg5paS68S27Rq-0GzM6FQNmDEclVqFZnexqVNcDoCT9XfJt608zRC0TUDcr6YVnaQsvkgo0OXDAkeu3y3wj94tzyHzKIFGjxu6C6Sb1MzBDFbpCwuZNG3mZcp8X1HnmSqak9JEBxnUnIFBDgWmSfOm_90n2boBBR6hGsvnlo0P_JItysDt8WHidK4Z7AX_lb2-T52PpX8ttVnC5AdY-M5pM5FCgdped0piPIPyDfKycSSRBO_PExqFKwWtQ1L_iDxS7OIBN6MNEXcdg35cDt6QjUEHhXP5sDSRNwnm4EXUtooIHPgJD9HZuAiyWV2u2EeGsUKkRCOevhJBa66_XxxqCgdld18ET9DWEazcrL0MQX51rAqq-0b3BXxJKnEMn75FdOLAtMG_hjZzU2j9Nc4bzzqlzdEflSswYlmsqAL5m8qJNcgr9IDLY1-eiGK3fVWeGYKSDvJ1Wv2Xkd8pIQxRGkyjtYnwXRL54cKi6ehE99odrOsgedqCYLNvKIg4mmeXvo928fQx-09p6YWZOYVl9LjCjSI4LXa7ACmS2rP0KggtJXbO4Ou-qI82mf7y7yHck3Q31NdLmtCO0O49l_8JY9vY8bWOx8tpi1etCqJC2WlAJdwt8

### create product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: {{api_key}}
Authorization: {{accessToken}}
x-client-id: 6570a602e2efdc61861060e4

{
  "title": "Product Electronic 01",
  "type": "electronics",
  "thumbnail": "http://image",
  "ratings": 5,
  "variants": [],
  "price": 1000,
  "quantity": 100,
  "attributes": {
    "manufacturer": "Manufacturer 01",
    "model": "Model 01",
    "color": "Red"
  },
  "description": "Product Electronic 01 Description"
}


### get draft products
GET {{url_dev}}/product/draft?limit=50&offset=0
Content-Type: application/json
x-api-key: {{api_key}}
Authorization: {{accessToken}}
x-client-id: 6570a602e2efdc61861060e4


### publish product
POST {{url_dev}}/product/publish
Content-Type: application/json
x-api-key: {{api_key}}
Authorization: {{accessToken}}
x-client-id: 656f540c7bb3dfc0b7895c08

{
  "productId": "6596e25aea2a9a282a81bbe4"
}


### search product
GET {{url_dev}}/product/search?q=Product
Content-Type: application/json
x-api-key: {{api_key}}
